server:
  port: 1212
spring:
  application:
    name: mq-message-rabbitadmin
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /vhost
    username: wsh
    password: wsh
    port: 5672
    connection-timeout: 10000
    template:
      mandatory: true
    #手动ACK
    listener:
      simple:
        acknowledge-mode: manual