server:
  port: 9097
spring:
  application:
    name: rabbitmq_redpack_demo
  rabbitmq:
    host: localhost
    virtual-host: /vhost
    username: wsh
    password: wsh
    publisher-confirms: true
    port: 5672
  datasource:
    username: root
    password: wsh0905
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_redpack?characterEncoding=utf8

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wsh.srpingboot.springboot_rabbitmq_redpack_demo.entity

logging:
  level:
    com:
      example:
        mapper : debug